#!/bin/bash
#
# Find the 50 slowest tests in your maven project and prints them as a CSV file
#
set -eo pipefail
[[ "${DEBUG:-}" ]] && set -x

main() {
  "$(dirname "$0")"/slowest-tests "$*" | sed 's/  //g' | sed 's/ /,/g'
}

main "$@"
