#!/bin/bash
#
# Find the 50 slowest tests in your maven project.
#
set -eo pipefail
[[ "${DEBUG:-}" ]] && set -x

main() {
  local folder="$*"
  [[ -z "$folder" ]] && folder="."
  grep -h "<testcase" "$(find "$folder" -iname "TEST-*.xml")" | \
    sed 's/<testcase time="\(.*\)" classname="\(.*\)" name="\(.*\)".*/\1 \2#\3/' | \
    sort -rn | head -n 50
}

main "$@"
