#!/bin/bash
#
# Find the 50 slowest tests in your maven project.
#
set -eo pipefail
[[ "${DEBUG:-}" ]] && set -x

extract() {
  local folder="$*"
  find "${folder:-.}" -iname "TEST-*.xml" | while read -r file; do
    grep -h "<testcase" "$file" | sed \
        -e 's/<testcase time="\(.*\)" classname="\(.*\)" name="\(.*\)".*/\1 \2#\3/'  \
        -e 's/<testcase name="\(.*\)" classname="\(.*\)" time="\(.*\)".*/\3 \2#\1/'
  done | sort -rn | head -n 50 | sed 's/  //g'
}

csv() {
  sed 's/ /,/g'
}

main() {
  if [[ "$1" = "-csv" ]]; then
    shift
    extract "$@" | csv
  else
    extract "$@"
  fi
}

main "$@"
